name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # your build folder will be created

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist       # change to your build folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
